# Generated by Django 4.0.10 on 2023-03-18 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('address_line_1', models.CharField(blank=True, max_length=512, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=512, null=True)),
                ('city', models.CharField(blank=True, max_length=32, null=True)),
                ('state', models.CharField(blank=True, max_length=32, null=True)),
                ('pincode', models.CharField(blank=True, max_length=8, null=True)),
                ('rate_per_hr', models.IntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('rate_per_hr', models.IntegerField(default=0)),
                ('approx_duration', models.IntegerField(default=0)),
                ('final_duration', models.IntegerField(default=0)),
                ('is_exited', models.BooleanField(default=False)),
                ('vehicle_type', models.CharField(blank=True, max_length=32, null=True)),
                ('vehicle_no', models.CharField(blank=True, max_length=16, null=True)),
                ('state', models.CharField(blank=True, max_length=16, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('parking_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parking_details.parkingplace')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
